use core::arch::asm;

use crate::x86::{PrivilegeLevel, SegmentSelector};

/// An entry in the Interrupt Descriptor Table specifying an interrupt/trap gate.
#[derive(Default)]
#[repr(C)]
#[repr(align(8))]
pub struct IdtEntry {
    offset_lo: u16,
    segment: SegmentSelector,
    resvd: u8,
    access: u8,
    offset_hi: u16,
}

impl IdtEntry {
    /// Creates a new IDT entry specifying a trap gate that will invoke the provided function.
    pub fn trap_gate(handler: extern "C" fn() -> !) -> Self {
        Self {
            offset_lo: (handler as u32 & 0xffff) as u16,
            segment: SegmentSelector::kernel_code(),
            resvd: 0,
            access: 0x8f | (PrivilegeLevel::Ring3 as u8) << 5,
            offset_hi: (handler as u32 >> 16) as u16,
        }
    }

    /// Creates a new IDT entry specifying an interrupt gate that will invoke the provided function.
    pub fn interrupt_gate(handler: extern "C" fn() -> !) -> Self {
        Self {
            offset_lo: (handler as u32 & 0xffff) as u16,
            segment: SegmentSelector::kernel_code(),
            resvd: 0,
            access: 0x8e,
            offset_hi: (handler as u32 >> 16) as u16,
        }
    }
}

/// The Interrupt Descriptor Table, which contains an array of interrupt/trap gates specifying
/// handlers for CPU exceptions and external interrupts.
#[derive(Default)]
#[repr(C)]
pub struct InterruptDescriptorTable {
    pub divide_error: IdtEntry,
    pub debug_exception: IdtEntry,
    pub non_maskable_interrupt: IdtEntry,
    pub breakpoint: IdtEntry,
    pub overflow: IdtEntry,
    pub bounds_check: IdtEntry,
    pub invalid_opcode: IdtEntry,
    pub coprocessor_not_available: IdtEntry,
    pub double_fault: IdtEntry,
    pub coprocessor_segment_overrun: IdtEntry,
    pub invalid_tss: IdtEntry,
    pub segment_not_present: IdtEntry,
    pub stack_fault: IdtEntry,
    pub general_protection_fault: IdtEntry,
    pub page_fault: IdtEntry,
    reserved: IdtEntry,
    pub math_fault: IdtEntry,
    pub alignment_check: IdtEntry,
    pub machine_check: IdtEntry,
    pub simd_error: IdtEntry,
    pub virtualization_exception: IdtEntry,
    pub control_protection_exception: IdtEntry,
    unused0: [IdtEntry; 10],
    pub irq: [IdtEntry; 16],
    unused1: [IdtEntry; 16],
    unused2: [IdtEntry; 32],
    unused3: [IdtEntry; 32],
    pub syscall: IdtEntry,
}

#[repr(packed)]
struct IdtPointer {
    #[allow(unused)]
    size: u16,
    base: u32,
}

// We need a static IDT descriptor because the lidt instruction can only use an absolute address.
#[unsafe(no_mangle)]
static mut IDT_PTR: IdtPointer = IdtPointer {
    size: size_of::<InterruptDescriptorTable>() as u16 - 1,
    base: 0,
};

impl InterruptDescriptorTable {
    /// Uses the `lidt` instruction to load the interrupt descriptor table.
    pub fn load(&'static self) {
        unsafe {
            IDT_PTR.base = &raw const *self as u32;
            asm!("lidt IDT_PTR", options(att_syntax));
        }
    }
}

/// Contains saved CPU state pushed onto the stack when an interrupt/exception occurs. This
/// structure contains both values pushed by the CPU as part of its internal interrupt handling, as
/// well as additional register state pushed by the boilerplate code generated by the handler macros
/// in this module.
#[derive(Default, Debug)]
#[repr(C)]
pub struct InterruptFrame {
    /// `DS` register value at the time of interrupt.
    ds: SegmentSelector,
    pad0: u16,
    /// `EDI` register value at the time of interrupt.
    pub edi: u32,
    /// `ESI` register value at the time of interrupt.
    pub esi: u32,
    /// `EBP` register value at the time of interrupt.
    pub ebp: u32,
    /// Kernel stack pointer at the time registers are pushed.
    _esp: u32,
    /// `EBX` register value at the time of interrupt.
    pub ebx: u32,
    /// `EDX` register value at the time of interrupt.
    pub edx: u32,
    /// `ECX` register value at the time of interrupt.
    pub ecx: u32,
    /// `EAX` register value at the time of interrupt.
    pub eax: u32,
    /// Error code pushed by the CPU during certain exceptions, otherwise set to 0.
    pub err: u32,
    /// `EIP` register value at the time of interrupt.
    pub eip: u32,
    /// `CS` register value at the time of interrupt.
    cs: SegmentSelector,
    pad1: u16,
    /// Flags register value at the time of interrupt.
    pub eflags: u32,
    /// User stack pointer at the time of interrupt. Only valid for interrupts that occur while
    /// executing in user mode.
    esp: u32,
    /// User stack segment register at the time of interrupt. Only valid for interrupts that occur
    /// while executing in user mode.
    ss: SegmentSelector,
    pad2: u16,
}

impl InterruptFrame {
    /// Creates an interrupt frame for initializing the stack of a newly created kernel mode task.
    fn kernel(eip: u32, esp: u32) -> Self {
        let mut frame = Self::default();
        frame.cs = SegmentSelector::kernel_code();
        frame.ds = SegmentSelector::kernel_data();
        frame.eip = eip;
        frame.esp = esp;
        frame
    }

    /// Creates an interrupt frame for initializing the stack of a newly created user mode task.
    fn user(eip: u32, esp: u32) -> Self {
        let mut frame = Self::default();
        frame.cs = SegmentSelector::user_code();
        frame.ds = SegmentSelector::user_data();
        frame.ss = SegmentSelector::user_data();
        frame.eflags = 1 << 9; // enable interrupts
        frame.eip = eip;
        frame.esp = esp;
        frame
    }

    /// Returns whether this interrupt frame belongs to a kernel mode execution context.
    fn is_kernel(&self) -> bool {
        self.cs.is_kernel()
    }

    /// Returns the user stack pointer if it is valid, otherwise `None`. It is only valid if the
    /// interrupt occurred while executing in user mode.
    fn get_user_esp(&self) -> Option<u32> {
        if self.is_kernel() {
            None
        } else {
            Some(self.esp)
        }
    }

    /// Sets the user stack pointer if it is valid, otherwise this function has no effect. It is
    /// only valid if the interrupt occurred while executing in user mode.
    fn set_user_esp(&mut self, esp: u32) {
        if self.is_kernel() {
            self.esp = esp;
        }
    }
}

/// Creates an `IdtEntry` that invokes a provided exception handler function. This macro generates
/// boilerplate assembly code to save CPU state, call the handler function, restore CPU state, and
/// perform `iret`, which is what the returned `IdtEntry` actually points to. Unlike
/// `exception_with_error_handler`, this macro variant should only be used for exceptions which do
/// not cause the CPU to push an error code onto the stack.
///
/// The provided exception handler should have the signature `extern C fn(&InterruptFrame)`.
macro_rules! exception_handler {
    ($func:ident) => {{
        use crate::x86::SegmentSelector;
        use crate::x86::idt::IdtEntry;

        #[unsafe(naked)]
        extern "C" fn wrapper() -> ! {
            core::arch::naked_asm!(
                // Push dummy error code, since the CPU didn't push one.
                "push $0",
                // Save registers to the interrupt frame.
                "pusha",
                "mov %ds, %eax",
                "push %eax",
                // Set the data segment registers to the kernel data segment.
                "mov ${kds}, %ax",
                "mov %ax, %ds",
                "mov %ax, %es",
                "mov %ax, %fs",
                "mov %ax, %gs",
                // Call the actual handler function, passing it a reference to the interrupt frame.
                "push %esp",
                "call {f}",
                "add $4, %esp",
                // Restore registers, including data segment registers.
                "pop %eax",
                "mov %ax, %ds",
                "mov %ax, %es",
                "mov %ax, %fs",
                "mov %ax, %gs",
                "popa",
                // Discard error code, since iret doesn't use it.
                "add $4, %esp",
                // Return from interrupt.
                "iret",
                kds = const SegmentSelector::kernel_data().as_u16(),
                f = sym $func,
                options(att_syntax)
            );
        }

        IdtEntry::trap_gate(wrapper)
    }};
}

pub(crate) use exception_handler;

/// Creates an `IdtEntry` that invokes a provided exception handler function. This macro generates
/// boilerplate assembly code to save CPU state, call the handler function, restore CPU state, and
/// perform `iret`, which is what the returned `IdtEntry` actually points to. Unlike
/// `exception_handler`, this macro variant should only be used for exceptions which cause the CPU
/// to push an error code onto the stack.
///
/// The provided exception handler should have the signature `extern C fn(&InterruptFrame)`.
macro_rules! exception_with_error_handler {
    ($func:ident) => {{
        use crate::x86::SegmentSelector;
        use crate::x86::idt::IdtEntry;

        #[unsafe(naked)]
        extern "C" fn wrapper() -> ! {
            core::arch::naked_asm!(
                // Save registers to the interrupt frame.
                "pusha",
                "mov %ds, %eax",
                "push %eax",
                // Set the data segment registers to the kernel data segment.
                "mov ${kds}, %ax",
                "mov %ax, %ds",
                "mov %ax, %es",
                "mov %ax, %fs",
                "mov %ax, %gs",
                // Call the actual handler function, passing it a reference to the interrupt frame.
                "push %esp",
                "call {f}",
                "add $4, %esp",
                // Restore registers, including data segment registers.
                "pop %eax",
                "mov %ax, %ds",
                "mov %ax, %es",
                "mov %ax, %fs",
                "mov %ax, %gs",
                "popa",
                // Discard error code, since iret doesn't use it.
                "add $4, %esp",
                // Return from interrupt.
                "iret",
                kds = const SegmentSelector::kernel_data().as_u16(),
                f = sym $func,
                options(att_syntax)
            );
        }

        IdtEntry::trap_gate(wrapper)
    }};
}

pub(crate) use exception_with_error_handler;

/// Creates an `IdtEntry` that invokes a provided page fault exception handler function. This macro
/// generates boilerplate assembly code to save CPU state, call the handler function, restore CPU
/// state, and perform `iret`, which is what the returned `IdtEntry` actually points to. Unlike the
/// other exception handler macros, this variant should only be used for the page fault exception.
///
/// The provided exception handler should have the signature
/// `extern C fn(VirtAddr, &InterruptFrame)`, with the additional `VirtAddr` argument being the
/// virtual address that triggered the page fault.
macro_rules! page_fault_handler {
    ($func:ident) => {{
        use crate::x86::SegmentSelector;
        use crate::x86::idt::IdtEntry;

        #[unsafe(naked)]
        extern "C" fn wrapper() -> ! {
            core::arch::naked_asm!(
                // Save registers to the interrupt frame.
                "pusha",
                "mov %ds, %eax",
                "push %eax",
                // Set the data segment registers to the kernel data segment.
                "mov ${kds}, %ax",
                "mov %ax, %ds",
                "mov %ax, %es",
                "mov %ax, %fs",
                "mov %ax, %gs",
                // Obtain the faulting address from CR2.
                "mov %cr2, %eax",
                // It's now safe to re-enable interrupts, if the interrupt flag was already set.
                "btl $9, {eflags}(%esp)",
                "jnc 2f",
                "sti",
                // Call the actual handler function, passing it the faulting address and a reference
                // to the interrupt frame.
                "2: push %esp",
                "push %eax",
                "call {f}",
                "add $4, %esp",
                // Restore registers, including data segment registers.
                "pop %eax",
                "mov %ax, %ds",
                "mov %ax, %es",
                "mov %ax, %fs",
                "mov %ax, %gs",
                "popa",
                // Discard error code, since iret doesn't use it.
                "add $4, %esp",
                // Return from interrupt.
                "iret",
                kds = const SegmentSelector::kernel_data().as_u16(),
                eflags = const core::mem::offset_of!(InterruptFrame, eflags),
                f = sym $func,
                options(att_syntax)
            );
        }

        // We use an interrupt gate for page fault so that the interrupt flag is cleared, ensuring
        // that a task switch cannot possibly overwrite the original CR2 value before we can push it
        // onto the stack.
        IdtEntry::interrupt_gate(wrapper)
    }};
}

pub(crate) use page_fault_handler;

/// Creates an `IdtEntry` that invokes a provided interrupt handler function. This macro generates
/// boilerplate assembly code to save CPU state, call the handler function, restore CPU state, and
/// perform `iret`, which is what the returned `IdtEntry` actually points to. Unlike the other
/// exception handler macros, this variant should be used for external hardware interrupts as the
/// interrupt enable flag will remain cleared when the handler is invoked.
///
/// The provided exception handler should have the signature `extern C fn(&InterruptFrame)`.
macro_rules! interrupt_handler {
    ($func:ident) => {{
        use crate::x86::SegmentSelector;
        use crate::x86::idt::IdtEntry;

        #[unsafe(naked)]
        extern "C" fn wrapper() -> ! {
            core::arch::naked_asm!(
                // Push dummy error code, since the CPU didn't push one.
                "push $0",
                // Save registers to the interrupt frame.
                "pusha",
                "mov %ds, %eax",
                "push %eax",
                // Set the data segment registers to the kernel data segment.
                "mov ${kds}, %ax",
                "mov %ax, %ds",
                "mov %ax, %es",
                "mov %ax, %fs",
                "mov %ax, %gs",
                // Call the actual handler function, passing it a reference to the interrupt frame.
                "push %esp",
                "call {f}",
                "add $4, %esp",
                // Restore registers, including data segment registers.
                "pop %eax",
                "mov %ax, %ds",
                "mov %ax, %es",
                "mov %ax, %fs",
                "mov %ax, %gs",
                "popa",
                // Discard error code, since iret doesn't use it.
                "add $4, %esp",
                // Return from interrupt.
                "iret",
                kds = const SegmentSelector::kernel_data().as_u16(),
                f = sym $func,
                options(att_syntax)
            );
        }

        IdtEntry::interrupt_gate(wrapper)
    }};
}

pub(crate) use interrupt_handler;
